# Generated by Django 3.2.23 on 2024-08-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_recentaction_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
